In [1]:
import pandas as pd

# 1) Load the two metadata CSVs with their full paths
meta_country = pd.read_csv(
    r"F:/Ironhack/Databases/Metadata_Country_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_38363.csv"
)
meta_indicator = pd.read_csv(
    r"F:/Ironhack/Databases/Metadata_Indicator_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_38363.csv"
)

# 2) Load the GDP data, skipping the 4-line preamble
gdp = pd.read_csv(
    r"F:/Ironhack/Databases/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_38363.csv",
    skiprows=4,
    low_memory=False      # keep this if you're on the default (C) engine
)

# 3) Normalize column names to simplify merges
for df in (gdp, meta_country, meta_indicator):
    df.columns = (
        df.columns
          .str.strip()
          .str.replace(' ', '_')
          .str.lower()
    )

# 4) Merge country metadata then indicator metadata
combined = (
    gdp
    .merge(meta_country,   on="country_code",   how="left")
    .merge(meta_indicator, on="indicator_code", how="left")
)

# 5) Inspect the result
print("Combined shape:", combined.shape)
print(combined.head())

Combined shape: (266, 79)
                  country_name country_code       indicator_name_x  \
0                        Aruba          ABW  GDP growth (annual %)
1  Africa Eastern and Southern          AFE  GDP growth (annual %)
2                  Afghanistan          AFG  GDP growth (annual %)
3   Africa Western and Central          AFW  GDP growth (annual %)
4                       Angola          AGO  GDP growth (annual %)

      indicator_code  1960      1961      1962      1963      1964      1965  \
0  NY.GDP.MKTP.KD.ZG   NaN       NaN       NaN       NaN       NaN       NaN
1  NY.GDP.MKTP.KD.ZG   NaN  0.469708  7.868623  5.622472  4.689533  5.159536
2  NY.GDP.MKTP.KD.ZG   NaN       NaN       NaN       NaN       NaN       NaN
3  NY.GDP.MKTP.KD.ZG   NaN  1.869637  3.725941  7.039191  5.364761  4.105616
4  NY.GDP.MKTP.KD.ZG   NaN       NaN       NaN       NaN       NaN       NaN

   ...  unnamed:_69                                             region  \
0  ...          NaN                          Latin America & Caribbean
1  ...          NaN                                                NaN
2  ...          NaN  Middle East, North Africa, Afghanistan & Pakistan
3  ...          NaN                                                NaN
4  ...          NaN                                 Sub-Saharan Africa

           incomegroup                                       specialnotes  \
0          High income                                                NaN
1                  NaN  26 countries, stretching from the Red Sea in t...
2           Low income  The reporting period for national accounts dat...
3                  NaN  22 countries, stretching from the westernmost ...
4  Lower middle income  The World Bank systematically assesses the app...

                     tablename  unnamed:_5       indicator_name_y  \
0                        Aruba         NaN  GDP growth (annual %)
1  Africa Eastern and Southern         NaN  GDP growth (annual %)
2                  Afghanistan         NaN  GDP growth (annual %)
3   Africa Western and Central         NaN  GDP growth (annual %)
4                       Angola         NaN  GDP growth (annual %)

                                         source_note  \
0  Gross domestic product is the total income ear...
1  Gross domestic product is the total income ear...
2  Gross domestic product is the total income ear...
3  Gross domestic product is the total income ear...
4  Gross domestic product is the total income ear...

                                 source_organization  unnamed:_4
0  Country official statistics, National Statisti...         NaN
1  Country official statistics, National Statisti...         NaN
2  Country official statistics, National Statisti...         NaN
3  Country official statistics, National Statisti...         NaN
4  Country official statistics, National Statisti...         NaN

[5 rows x 79 columns]

In [2]:
combined

,country_name,country_code,indicator_name_x,indicator_code,1960,1961,1962,1963,1964,1965,...,unnamed:_69,region,incomegroup,specialnotes,tablename,unnamed:_5,indicator_name_y,source_note,source_organization,unnamed:_4
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Latin America & Caribbean,High income,NaN,Aruba,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
1,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.469708,7.868623,5.622472,4.689533,5.159536,...,NaN,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Middle East, North Africa, Afghanistan & Pakistan",Low income,The reporting period for national accounts dat...,Afghanistan,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
3,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.869637,3.725941,7.039191,5.364761,4.105616,...,NaN,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Europe & Central Asia,Upper middle income,NaN,Kosovo,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
262,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Middle East, North Africa, Afghanistan & Pakistan",Low income,The World Bank systematically assesses the app...,"Yemen, Rep.",NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
263,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.844734,6.177931,7.373709,7.939609,6.122798,...,NaN,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
264,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,...,NaN,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN
265,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.316157,1.434471,6.244345,-1.106172,4.910571,...,NaN,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe,NaN,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN

In [5]:
combined.columns

Index(['country_name', 'country_code', 'indicator_name_x', 'indicator_code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', 'unnamed:_69', 'region', 'incomegroup', 'specialnotes',
       'tablename', 'unnamed:_5', 'indicator_name_y', 'source_note',
       'source_organization', 'unnamed:_4'],
      dtype='object')

In [11]:
brazil_rows = combined[ combined['country_name'] == 'Brazil' ]
brazil_rows[['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971']].sum().median()

6.650000000000009